# Generated by Django 6.1 on 2026-08-11 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True, default='', max_length=1000, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('image', models.ImageField(upload_to='upload/product/')),
                ('category_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category', verbose_name='category_title')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('count', models.SmallIntegerField()),
                ('address', models.CharField(max_length=300)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('در انتظار پرداخت', 'Unpaid'), ('پرداخت شده', 'Paid'), ('در حال بررسی', 'Processing'), ('رد شده', 'Rejected'), ('تایید شده', 'Confirmed'), ('لغو شده', 'Canceled'), ('انجام شده', 'Done')], default='در انتظار پرداخت', max_length=30)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.customer', verbose_name='customer_id')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='product_id')),
            ],
        ),
    ]
