# Generated by Django 6.1 on 2026-08-11 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('UNPAID', 'در انتظار پرداخت'), ('PAID', 'پرداخت شده'), ('PROCESSING', 'در حال بررسی'), ('REJECTED', 'رد شده'), ('CONFIRMED', 'تایید شده'), ('CANCELED', 'لغو شده'), ('DONE', 'انجام شده')], default='UNPAID', max_length=30),
        ),
    ]
