# Generated by Django 6.1 on 2026-08-13 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_product_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_stock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
